application: cronhooks
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /cron/.*
  script: main.py
  login: admin

- url: /post/[a-z0-9]+
  script: main.py
  login: admin

- url: /.*
  script: main.py
